/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

/**
 *
 * @author sath
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customersButton = new javax.swing.JButton();
        partiesButton1 = new javax.swing.JButton();
        addOnsButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        saleButton = new javax.swing.JButton();
        addOnsButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 60, 117));

        customersButton.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        customersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_icons/customers.png"))); // NOI18N
        customersButton.setText("Customers");
        customersButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        customersButton.setContentAreaFilled(false);
        customersButton.setFocusPainted(false);
        customersButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customersButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        partiesButton1.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        partiesButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_icons/parties.png"))); // NOI18N
        partiesButton1.setText("Parties");
        partiesButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        partiesButton1.setContentAreaFilled(false);
        partiesButton1.setFocusPainted(false);
        partiesButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        partiesButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        addOnsButton.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        addOnsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_icons/addons_and_catering.png"))); // NOI18N
        addOnsButton.setText("Others");
        addOnsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addOnsButton.setContentAreaFilled(false);
        addOnsButton.setFocusPainted(false);
        addOnsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOnsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        usersButton.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        usersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_icons/users.png"))); // NOI18N
        usersButton.setText("Users");
        usersButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        usersButton.setContentAreaFilled(false);
        usersButton.setFocusPainted(false);
        usersButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usersButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        saleButton.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        saleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_icons/sale.png"))); // NOI18N
        saleButton.setText("Sale");
        saleButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        saleButton.setContentAreaFilled(false);
        saleButton.setFocusPainted(false);
        saleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        addOnsButton1.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        addOnsButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_icons/addons_and_catering.png"))); // NOI18N
        addOnsButton1.setText("Others");
        addOnsButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addOnsButton1.setContentAreaFilled(false);
        addOnsButton1.setFocusPainted(false);
        addOnsButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOnsButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usersButton)
                    .addComponent(customersButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(partiesButton1)
                        .addGap(130, 130, 130)
                        .addComponent(addOnsButton)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(saleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addOnsButton1)
                        .addGap(85, 85, 85))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customersButton)
                    .addComponent(addOnsButton)
                    .addComponent(partiesButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usersButton)
                    .addComponent(addOnsButton1)
                    .addComponent(saleButton))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOnsButton;
    private javax.swing.JButton addOnsButton1;
    private javax.swing.JButton customersButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton partiesButton1;
    private javax.swing.JButton saleButton;
    private javax.swing.JButton usersButton;
    // End of variables declaration//GEN-END:variables
}
